from .prospect import WriteProspectSerializer, ListProspectSerializer, DetailProspectSerializer
from .client import WriteClientSerializer, ListClientSerializer, DetailClientSerializer
from .contract import WriteContractSerializer, ListContractSerializer, DetailContractSerializer