# Generated by Django 4.2.1 on 2023-06-14 19:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_managemember_options_alter_salemember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Prenom')),
                ('last_name', models.CharField(max_length=25, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telephone fix')),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telephone portable')),
                ('company_name', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.company')),
            ],
            options={
                'verbose_name': 'Prospect',
            },
            bases=('crm.company',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.company')),
                ('sale_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clients', to='authentication.salemember', verbose_name='Conseiller(ère)')),
            ],
            options={
                'verbose_name': 'Client',
            },
            bases=('crm.company',),
        ),
    ]
