# Generated by Django 4.2.1 on 2023-06-21 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_company_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='statut')),
                ('amount', models.FloatField(verbose_name='Montant')),
                ('payment_due', models.DateTimeField(verbose_name='Date de paiement')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='crm.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Contrat',
            },
        ),
    ]
