# Generated by Django 4.2.1 on 2023-06-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_managemember_options_alter_salemember_options_and_more'),
        ('crm', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='authentication.supportmember', verbose_name='Support'),
        ),
    ]
