# Generated by Django 4.2.1 on 2023-06-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_event_support_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('set_support_event', 'Can (set/change) support contact')], 'verbose_name': 'Évenement'},
        ),
    ]
